In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [13]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [14]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [15]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [21]:
np.linspace(1,6,5)

array([ 1.  ,  2.25,  3.5 ,  4.75,  6.  ])

In [22]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [23]:
np.random.rand(5)

array([ 0.16151456,  0.25034748,  0.06837694,  0.43259661,  0.94711261])

In [24]:
np.random.rand(5,6)

array([[ 0.9959154 ,  0.2406775 ,  0.89947227,  0.11117299,  0.0671918 ,
         0.17154948],
       [ 0.08493948,  0.83161831,  0.14527955,  0.89125736,  0.62144079,
         0.2894339 ],
       [ 0.25066694,  0.53952907,  0.61819593,  0.43232234,  0.42050723,
         0.6700265 ],
       [ 0.54044625,  0.66006144,  0.27134967,  0.01072863,  0.35112371,
         0.39920965],
       [ 0.94537391,  0.90688547,  0.7335725 ,  0.93751069,  0.34642109,
         0.977958  ]])

In [25]:
np.random.randn(2)

array([-0.20409216, -0.50243662])

In [26]:
np.random.randn(2,4)

array([[-0.27361434,  2.23882135, -1.24613746, -1.75677392],
       [ 0.19209327, -0.87343175, -0.67256511,  0.14749232]])

In [28]:
np.random.randint(1,100, 10)

array([27, 14,  8, 90, 93, 47, 12, 69, 47, 13])

In [29]:
arr =  np.arange(0,25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
random_array = np.random.randint(0,50,10)

In [32]:
random_array

array([20, 19, 47, 29, 40, 35, 26, 36, 48, 15])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
random_array.max()

48

In [36]:
random_array.min()

15

In [38]:
random_array.argmax() # Returns index of largest element

8

In [ ]:
random_array.argmin #return index of smallest 